import {
  Leaf,
  Flower,
  TreePine,
  Mountain,
  Sun,
  Moon,
  Sprout,
  Cloud,
  Snowflake,
  Wind,
  Clover,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Cloudy,
  Droplets,
  Rainbow,
  Tornado,
  Grape,
  Award,
  Bike,
  Dumbbell,
  Flag,
  Goal,
  Medal,
  Trophy,
  Sunrise,
  Sunset,
  Thermometer,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const iconCategories: Record<string, LucideIcon[]> = {
  nature: [Leaf, Flower, TreePine, Mountain, Sun, Moon, Sprout, Cloud, Snowflake, Wind, Clover],
  weather: [
    Cloud,
    CloudDrizzle,
    CloudFog,
    CloudHail,
    CloudLightning,
    CloudMoon,
    CloudMoonRain,
    CloudOff,
    CloudRain,
    CloudRainWind,
    CloudSnow,
    CloudSun,
    CloudSunRain,
    Cloudy,
    Droplets,
    Moon,
    Rainbow,
    Snowflake,
    Sun,
    Sunrise,
    Sunset,
    Thermometer,
    Tornado,
    Wind,
  ],
  seasons: [Grape, Leaf, Snowflake, Sun],
  sports: [Award, Bike, Dumbbell, Flag, Goal, Medal, Trophy],
};

export const getAllIcons = (): LucideIcon[] => {
  return Object.values(iconCategories).flat();
};
